services:
  db:
    build: scripts/postgis-arm-image
    environment:
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - SCHEMA_NAME=public
      - WAL_LEVEL=logical
      - REPLICATION_USER=postgres
      - REPLICATION_PASS=postgres
      - PGSSLMODE=allow
      - REPLICATION='true'
    volumes:
      - "pg_data_m1:/var/lib/postgresql/"

volumes:
  pg_data_m1:
