services:
  db:
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  hasura:
    ports:
      - "8080:8080"

  middleware:
    ports:
      - "3000:3000"

volumes:
  pg_data:
