#!/bin/sh

BASE_DIR="$(cd "$(dirname "$0")"; pwd)";

FULL_PATH="$BASE_DIR"/../hasura-backend/sql

echo "$FULL_PATH"

sqrly watch --path "$FULL_PATH" --db postgres://postgres:postgres@localhost:5432/postgres